# Generated by Django 3.0 on 2020-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='size',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_file',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='is_asset_image',
            field=models.BooleanField(default=True),
        ),
    ]
