# Generated by Django 3.0 on 2020-05-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200523_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grapher',
            name='email',
        ),
        migrations.AlterField(
            model_name='story',
            name='grapher_id',
            field=models.IntegerField(),
        ),
    ]
