# Generated by Django 3.0 on 2020-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20200523_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
